# Generated by Django 5.0.6 on 2024-10-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nis_app', '0002_country_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='flags/'),
        ),
    ]
