# Generated by Django 5.0.6 on 2024-10-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nis_app', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
