# Generated by Django 5.0.6 on 2024-10-08 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nis_app', '0005_message_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='name',
            new_name='name_en',
        ),
    ]
