# Generated by Django 5.0.6 on 2024-10-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nis_app', '0006_rename_name_country_name_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='description',
            new_name='description_en',
        ),
        migrations.AddField(
            model_name='country',
            name='name_ja',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='name_tk',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
