# Generated by Django 5.0.6 on 2024-10-08 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nis_app', '0008_country_description_ja_country_description_tk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='innovationpractice',
            old_name='description',
            new_name='description_en',
        ),
    ]
