# Generated by Django 5.0.6 on 2024-10-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nis_app', '0010_innovationpractice_description_ja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovationpractice',
            name='huge_data_en',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='innovationpractice',
            name='huge_data_ja',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='innovationpractice',
            name='huge_data_tk',
            field=models.TextField(default=1),
        ),
    ]
