# Generated by Django 5.0.6 on 2024-10-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nis_app', '0011_innovationpractice_huge_data_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovationpractice',
            name='huge_data_en',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='innovationpractice',
            name='huge_data_ja',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='innovationpractice',
            name='huge_data_tk',
            field=models.TextField(),
        ),
    ]
