# Generated by Django 5.0.6 on 2024-10-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nis_app', '0012_alter_innovationpractice_huge_data_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovationpractice',
            name='huge_data_en',
        ),
        migrations.RemoveField(
            model_name='innovationpractice',
            name='huge_data_ja',
        ),
        migrations.RemoveField(
            model_name='innovationpractice',
            name='huge_data_tk',
        ),
        migrations.AddField(
            model_name='country',
            name='huge_data_en',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='country',
            name='huge_data_ja',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='country',
            name='huge_data_tk',
            field=models.TextField(default=1),
        ),
    ]
