# Generated by Django 5.0.6 on 2024-10-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nis_app', '0013_remove_innovationpractice_huge_data_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='huge_data_en',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='country',
            name='huge_data_ja',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='country',
            name='huge_data_tk',
            field=models.TextField(),
        ),
    ]
